apiVersion: v1 
kind: Service
metadata:
  name: backend
  labels:
    group: movies
spec:
  selector:
    app: movie-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8000
  type: LoadBalancer